### ISSUE TITLE
Image not loading,

### ISSUE THREAD

**Issue by ayush-wd** [srinidhibhat45/srinidhi-bhat-portfolio#43]
The image in the graphic designing card of the "some of my projects and works" section is not loading.

**Comment by srinidhibhat45** [comment]
hey @ayush-wd it looks fine to me

![image](https://user-images.githubusercontent.com/60350682/183501158-c78dfc93-2822-4d6e-81e7-edf284960793.png)

**Comment by ayush-wd** [comment]
It must be a network problem for me then. Also, I am a front-end developer and would like to work with you on this open-source project.
